!Blockwork
project   : hex8
site      : ./site.yaml
tooldefs  :
  - infra.tools.objstore
  - infra.tools.compilers
  - infra.tools.simulators
  - infra.tools.python
workflows :
  - infra.workflows.lint
config    :
  - infra.config.module
