name: Hex8 CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  flow:
    name: Flow
    runs-on: ubuntu-22.04
    steps:
      # 1. Checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      # 2. Install Python
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      # 3. Install Poetry
      - name: Install Poetry
        shell: bash
        run: python3 -m pip install poetry
      # 4. Bootstrap
      - name: Blockwork Bootstrap
        uses: ./.github/composites/shell
        with:
          script: bw bootstrap
      # 5. Simple environment test
      - name: Test Blockwork
        uses: ./.github/composites/shell
        with:
          script: bw exec -- echo "ready"
