name: Hex8 CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  flow:
    name: Flow
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      # 1. Checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      # 2. Install Python
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      # 3. Install Poetry
      - name: Install Poetry
        shell: bash
        run: python3 -m pip install poetry
      # 4. Authenticate with the object store
      - name: Authenticate with R2
        uses: ./.github/composites/shell
        with:
          script: |
            bw tool objstore.authenticate ${{ secrets.R2_ENDPOINT_URL }} \
                                          ${{ secrets.R2_ACCESS_KEY }} \
                                          ${{ secrets.R2_SECRET_KEY }} \
                                          ${{ secrets.R2_BUCKET }}
      # 5. Bootstrap
      - name: Blockwork Bootstrap
        uses: ./.github/composites/shell
        with:
          script: bw bootstrap
      # 6. Simple environment test
      - name: Test Blockwork
        uses: ./.github/composites/shell
        with:
          script: bw exec -- echo "ready"
      # 7. Lint the design
      - name: Linting
        uses: ./.github/composites/shell
        with:
          script: bw wf lint -t leaf/hex8 -p v1
